
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sannidhya
 */
public class HIS extends javax.swing.JFrame {
    static String DB_URL = "jdbc:mysql://localhost:3306/lib";
   static final String USER = "root";
   static final String PASS = "12345678";
    /**
     * Creates new form Issue
     */
   public HIS(){}
    
    public HIS(String h ,String i) {
        initComponents();
        {
            jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                String q ="""
                          select b.name as bookname,b.id ,u.name ,u.userid ,bu.Date from book as b,bookuser as bu,user as u
                          where b.id = bu.idb and u.userid = bu.userid
                          order by bu.Date DESC
                          limit 5;""";
                
                try(
            
              Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
         Statement stmt = conn.createStatement();
         
                        ) {
         // Extract data from result set
         String data ="<html>";
         if(h.equals("h") && i.equals("-1")){
         ResultSet rs = stmt.executeQuery(q);
         System.out.println(data+" " +h+  " " + i );
         int o = 1;
         while (rs.next()) {
            data = data + o++ +  ") name:  "+rs.getString("name") + "   id:      " + rs.getInt("userid") +"   Bookname:  "+ rs.getString("bookname") +
               "   Date:       "     +rs.getDate("Date") + "<br/><br/>";

         }
         }
         if(h.equals("u") && !i.equals("-1")){
             q = "select * from user where userid = "+i+";";
             ResultSet rs = stmt.executeQuery(q);
         
         
         while (rs.next()) {
            data = data + "name:"+rs.getString("name") + "   id:" + rs.getInt("userid") + "<br/><br/>";

         }
         }
         if(h.equals("b") && !i.equals("-1")){
             System.out.println(i);
             q = "select * from book where name = \"" +i+"\";";
             ResultSet rs = stmt.executeQuery(q);
         
         int y = 1;
         while (rs.next()) {
            data = data +y++ + ") name:"+rs.getString("name") +"   Author: "+ rs.getString("author")+"   id:" + rs.getInt("id") + "<br/><br/>";

         }
         }
         data = data + "</html>";
         jLabel4.setText(data);
         System.out.println(data+" " +h+  " " + i );
         
      } catch (SQLException ef) {
         ef.printStackTrace();
      }
                //System.out.println(s1+pass);
            }
        });
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 660, 300));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Required information are as follows");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 310, 30));

        jButton1.setBackground(new java.awt.Color(102, 51, 0));
        jButton1.setFont(new java.awt.Font("YouYuan", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("show");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\sannidhya\\java\\swing p\\library\\res\\bg.jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 777, 442));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
